export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const SAY_HELLO = 'SAY_HELLO';
export const USER_FETCHED = 'USER_FETCHED';

export const ENTITY_REPOSITORY_HAS_CHANGED = 'ENTITY_REPOSITORY_HAS_CHANGED';

export const ROUTER_INIT = 'ROUTER_INIT';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';
